### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by malsony** [drewlander/mailonacircle#3]
1. Is Roundcube included, and, if not, will you include it in future?
2. Does the system support virtual domain, and, are the .conf files ready for virtual domain email hosting?
3. For those who are running existing LEMP (or LEMPA) stacks, how should they chose not to install MySQL (Mariadb) but just enter the password of root for DB, instead?

Anyway, this is nice, as there are only Ubuntu versions out there, thanks for your works!

**Comment by drewlander** [comment]
wow I did not expect anyone to even see this! haha
to answer your questions:
1) no it is not, but it absolutely could be. I can work on that next
2) It does support virtual domains but not immediately. It could easily be done by adding sql rows via a config file, right now it is all manually done via postfixadmin after installation. 
3). Right now, it will install mysql anyway, there is no way to not do that right now. It assumes a fresh machine. overrides per "service" is a good idea, that can definitely be added.

Thanks for the feedback! I will get those things addressed!

**Comment by malsony** [comment]
I am more than happy if I can help anyway (the fact is that I can't code at this moment and am still reading some 101 books). 

Actually, I am thinking of a CLI interface of this system:
1. Basic E-mail apps (postfix, dovecot, spamassassin, clamav...);
2. Generate necessary SSL certificates or ask the user for location of existing certificates and keys;
3. Check if MySQL/Mariadb is installed (or running), or ask the user whether to install MySQL/Mariadb;
4. Check if web server is installed (or running), or ask the user which server to install Nginx, Apache, Lighttpd, plus respecting PHP;
5. Ask the user if postfixadmin is needed, if so, install it; but if not, provide a series of CLI programs to let the user to: add domain, e-mail user, alias, forwarder; change alias, password; etc... isn't that crazy? I know another project provides CLI to allow admins to do so;
6. Ask the user if Roundcube (or other webmail clients) is needed.

Maybe the order of step 3 and 4 can be swapped? 

Anyway, I would like to share more why I am thinking of this:
1. Some mid/large companies use existing DB server and maybe MySQL is not needed so badly; and maybe they do not want webmail client on the same server at all, they can either fetch the email with mobile devices or from a webmail client on another server;
2. This idea is so flexible so that it can fit a fresh server or one with dynamic web hosting stacks no matter if it is from a small firm or a growing company.

What do you think?

**Comment by drewlander** [comment]
All of your ideas are good ideas. This was just a simple way to allow people to have something similar (albeit less feature complete) with mailinabox. Most medium/large companies would not (and I would insist) they not use this recipe (no redundancy, backups, doesn't scale, etc...) So making this more "enterprise" ready is a good idea, as long as its stays simple to use and configure. 
The steps to begin what you have described would be:
1. Configure attributes so chef knows what to do and what not to do
  e.x. if the attribute exists for a mysql connection, use that and do not install a new mysql instance, etc..
2. configure a cli that can create/modify attributes file to be used by chef-solo
3. Modify recipe to allow nginx/apache (lighttpd if some free time) this is only needed if running postfixadmin
4. Make a cli that can do the mail configuration that would work also work if postfixadmin is enabled 
 e.x.  if postfixadmin, add entries to mysql. If not, add to transport, aliases,etc.. in /etc/postfix
5. any cli usage must be scriptable, not just prompting a user

That would work. Unfortunately I do not have a lot of time currently so feel free to go crazy with this. Anything that improves something is always welcome!

**Comment by malsony** [comment]
Already forked and start to read your codes. :laughing:

**Comment by drewlander** [comment]
👍

**Comment by drewlander** [comment]
closing this issue. @malsony  feel free to make new tickets for each individual item
