### ISSUE TITLE
Some premises.

### ISSUE THREAD

**Issue by malsony** [drewlander/mailonacircle#4]
1. `php-imap` package is not included in default yum repo. How about include an installation of `epel-release` and an update before "cooking"? I saw EPEL is included in the README.md after installing postfixadmin, but maybe it would be better if `epel-release` is required before "cooking".
2. Got an error message when running the last two commands in recipes/configure_postfixadmin.rb, guess it was due to Selinux settings (or lack of its components?). A work-around is disable Selinux and comment out those two commands, any idea?

**Comment by drewlander** [comment]
we can have it automatically install epel, aboslutely.
I would rather we work with selinux than just turn it off. I am a firm believer in: http://stopdisablingselinux.com/

**Comment by malsony** [comment]
Thanks for the information! Will find out more benefits brought by SELinux.

**Comment by malsony** [comment]
Looked for some basic intro. of SELinux, and guess that my second problem was due to missing of `semanage`. Just did some research, and they say running `yum install -y policycoreutils-python` can bring `semanage` to the system. Any way, I will give it a try and "cook" again to see how it "tastes". :laughing:

**Comment by drewlander** [comment]
selinux fixed in previous commits
epel fixed in dd32263271fc2415843ff286b4a4399a0567eeea
